CREATE DATABASE measurements;
USE measurements;
CREATE TABLE rawdata (
 id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
 sensor_direction INT NOT NULL DEFAULT 0,
 sensorvalue_x FLOAT NOT NULL DEFAULT 0,
 sensorvalue_y FLOAT NOT NULL DEFAULT 0,
 sensorvalue_z FLOAT NOT NULL DEFAULT 0
);